name: Build Windows EXE with PyInstaller

on:
  push:
    branches:
      - main  # oder dein Branch, auf dem du den Build starten möchtest

jobs:
  build:
    runs-on: windows-latest  # Wir verwenden ein Windows-Runner für den Build-Prozess

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Verwende deine Python-Version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller openpyxl  # Installiere pyinstaller und openpyxl

    - name: Add .ico file to resources
      run: |
        mkdir resources
        cp GPX_Auslesen_TdF.ico resources/

    - name: Build Windows EXE with PyInstaller
      run: |
        pyinstaller --onefile --icon=resources/GPX_Auslesen_TdF.ico --distpath dist --workpath build GPX_auslesen.py

    - name: Upload the EXE artifact
      uses: actions/upload-artifact@v2
      with:
        name: GPX_Auslesen_Exe
        path: dist/GPX\ Auslesen.exe
