name: Build Windows EXE with PyInstaller

on:
  push:
    branches:
      - main  # oder dein Branch, der für den Build verwendet werden soll

jobs:
  build:
    runs-on: windows-latest  # Windows-Runner, um die EXE zu erstellen

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Holen des Repositories

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Die Python-Version, die du verwendest

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller openpyxl  # Installiere PyInstaller und openpyxl

    - name: Build Windows EXE with PyInstaller
      run: |
        pyinstaller --onefile --icon=GPX_Auslesen_TdF.ico --distpath dist --workpath build GPX_auslesen.py  # Erstellen der EXE mit Icon

    - name: Upload the EXE artifact
      uses: actions/upload-artifact@v2
      with:
        name: GPX_Auslesen_Exe
        path: dist/GPX\ Auslesen.exe  # Pfad zur erstellten EXE
